#spring.datasource.url=jdbc:${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
# Configuração do tamanho do lote
#spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.jdbc.batch_size=1000
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
## Habilitar processamento em lote no Hibernate
#spring.jpa.properties.hibernate.jdbc.batch_size_for_inserts=10
## Estratégia de nomenclatura do Hibernate
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

#JWT
forum.jwt.expiration=86400000
forum.jwt.secret=S@%wHsqyaB4%t#nwgf#xtdpK%5wsPMkodc#uKzWBDc&5zzJxH^

#limite máximo do arquivo em bytes
spring.servlet.multipart.max-file-size=10MB

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Habilita o log do Hibernate
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE