#spring.datasource.url=jdbc:${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=1000

#JWT
forum.jwt.expiration=86400000
forum.jwt.secret=S@%wHsqyaB4%t#nwgf#xtdpK%5wsPMkodc#uKzWBDc&5zzJxH^

#limite máximo do arquivo em bytes
spring.servlet.multipart.max-file-size=10MB