spring.datasource.url=jdbc:mysql://suasorte-db.c9zbrltdmpgr.us-east-2.rds.amazonaws.com:3306/bpadash
spring.datasource.username=userdbss
spring.datasource.password=78f77cfc780794aA#W
spring.jpa.hibernate.ddl-auto=update

server.ssl.key-store:/etc/letsencrypt/live/bpadash.com/keystore.p12
server.ssl.key-store-password: 78f77cfc780794aA#W
server.ssl.keyStoreType: PKCS12
security.require-ssl=true

server.port: 9090

# SSL, post 465
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory